# Generated by Django 6.0.1 on 2026-01-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(max_length=100)),
                ('title_words', models.JSONField()),
                ('subtitle', models.TextField()),
                ('primary_cta_text', models.CharField(max_length=50)),
                ('primary_cta_link', models.CharField(max_length=100)),
                ('secondary_cta_text', models.CharField(max_length=50)),
                ('secondary_cta_link', models.CharField(max_length=100)),
            ],
        ),
    ]
