# Generated by Django 6.0.1 on 2026-02-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', 'Work'), ('education', 'Education'), ('award', 'Award')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
